# PRUEBAS BÁSICAS

In [47]:
#Multiplicaciones y sumas
4.0*0.15 + 4.5*0.35 +3.0*0.40 + 4.8*0.1

3.855

In [48]:
quices=4.0
proyectos=4.5
parciales=3.0
tareas=4.8

In [24]:
notadefinitiva= quices*.15 + proyectos*.35 + parciales*.40 + tareas*.10

In [25]:
#Resultado de la variable definida
print (notadefinitiva)

3.855


In [26]:
quices

4.0

In [28]:
who

notadefinitiva	 np	 numpy	 parciales	 proyectos	 quices	 tareas	 


In [29]:
ejes=4
rodamientos=6
engranajes=2

In [30]:
objetos= ejes+rodamientos+engranajes

In [31]:
print (objetos)

12


In [32]:
ejes=6

In [33]:
print(objetos)

12


In [34]:
objetos

12

# CALCULO DE PI

In [35]:
x=np.random.rand(5000000,1)

In [36]:
y=np.random.rand(5000000,1)

In [37]:
x

array([[ 0.66519531],
       [ 0.98153441],
       [ 0.42384749],
       ..., 
       [ 0.22421476],
       [ 0.5421766 ],
       [ 0.27385192]])

In [38]:
y

array([[ 0.69457784],
       [ 0.31389992],
       [ 0.09368983],
       ..., 
       [ 0.88179628],
       [ 0.91405133],
       [ 0.53818739]])

In [39]:
corx= x**2

In [40]:
cory= y**2

In [41]:
hipo= (corx + cory)**(1/2) 

In [42]:
hipo

array([[ 0.96172927],
       [ 1.03050616],
       [ 0.43407888],
       ..., 
       [ 0.90985545],
       [ 1.06275363],
       [ 0.60385473]])

In [43]:
sol=0
for i in range (0,5000000):
    if hipo[i]<1:
        sol= sol+1
        

In [44]:
sol

3926906

In [45]:
variable= 4*sol/5000000

In [46]:
variable

3.1415248